### ISSUE TITLE
Brainhack Reviewer Comments

### ISSUE THREAD

**Issue by leiliew** [Brainhack-Proceedings-2015/Badhwar_HBM_Brainspell#1]
Overall, this proceeding is clearly written and well-organized. The work completed during this Brainhack project is well-done and will likely be of great benefit to the neuroimaging community. Given that, the authors might take my comments as simply suggestions to potentially strengthen the impact and reach of this proceeding for a slightly broader audience. 

**Introduction:** 
I might reorganize a bit as follows: “The past several decades have seen an explosive growth in the number of published neuroimaging studies. In juxtaposition, there has also been a soaring demand for freely available and openly accessible ways to search, organize and repurpose this growing database of studies to conduct meta-analyses, support current hypotheses and test new hypotheses. Here we report on developments made to Brainspell1, one of several web-based initiatives (along with tools such as BrainMap2, NeuroVault3, and Neurosynth4) that allows individuals to search through and organize massive numbers of neuroimaging studies and results in meaningful ways. 

Unique from other databases, Brainspell (http://brainspell.org) is the first web-based initiative to allow individuals to manually edit, annotate, and curate machine-parsed data. It also allows users to manually extend the database via a crowdsourcing interface (this part was a bit unclear to me?). The current Brainhack project added and beta-tested ten enhancements to the Brainspell interface that would (a) provide supplementary manual data editing options; (b) facilitate more efficient manual (?) database extension, and (c) aid meaningful organization of data (this is also unclear to me). “

*_Approach: *_
The transition from talking about Brainspell to talking about Github was a bit unclear to me. By putting this in the approach, did the authors mean to say something like, “Enhancements to Brainspell under the current project were carried out in GitHub. Brain spell uses GitHub to manage the client and server code, and to coordinate its development. The following GitHub functionalities were particularly useful: xxx..”

**Results:**
A. Supplementary manual data edit options - Here I would divide this to discuss a) “edit feedback”, aka "Feedback indicating when..." and then b) additional edits allowed, aka "Title and caption fields now allow symbols, etc." The other sections read well.

**Conclusion and Discussion**: 
I would keep the first paragraph about what was done, and also add a sentence like “Our goal with these enhancements was to extend the functionality and ease of use of Brainhack for curating machine-parsed neuroimaging data from a wide database of studies” or something like that. Then I would remove the next paragraph on GitHub, which seems to come a bit out of nowhere? If anything, I would put this Github paragraph into the approach, as it directly addresses my question on why you’re talking about GitHub. Or, if you want to keep it in the conclusions, I might add a transition sentence for why you're going back to discuss GitHub again (e.g., "Notably, these enhancements could not have been made without key functionalities from Github")

**Figure:**
Good figure! For future use (I’m not sure if this exists or not, and certainly is not necessary for this submission), it would be very helpful to have a quick 3-5 min tutorial video on how to use Brainspell and all the functions. 

Please let me know if you have questions or comments!

Best wishes, and good work,
Lei

**Comment by amanbadhwar** [comment]
Dear Lei,

Thank you for your helpful comments. We have now incorporated many of your suggestions.

Best,
Aman

**Comment by npnl** [comment]
Looks great - I think this is ready to go!
