### ISSUE TITLE
Review from Michael P. Milham

### ISSUE THREAD

**Issue by ccraddock** [Brainhack-Proceedings-2015/Badhwar_HBM_Brainspell#2]
Overall, this submission appears to be appropriate for the special issue and is informative of the project. One stylistic concern is the first paragraph throws out a number of initiatives, and then just starts talking about Brainspell…feels a little weird from a transition perspective.

**Comment by amanbadhwar** [comment]
Dear Michael,

Thank you for taking the time to review our Brainhack project report. We have now reworked the paragraph so that it flows better.

Best,
Aman
